---
title: "graphs"
output:
  html_document:
    df_print: paged
    toc: false
---

```{r setup, include = FALSE}
# INSTALL
# knitr::opts_chunk$set(cache = TRUE)

# LOAD
suppressWarnings(source("./R/sources.R"))
# variables globales
begin_time<-Sys.time()

# FCTS

```

[retour](./../index.html)

<!-- -->

|                             |                               |                             |
|-----------------------------|-------------------------------|-----------------------------|
| [allListe](./allListe.html) | [wordcloud](./wordcloud.html) | [graph](./mygraph.html)     |
| [sumup](./sumup.html)       | [summary](./summary.html)     | [sumUpAll](./sumUpAll.html) |

------------------------------------------------------------------------

### hhmm

```{r saiep, echo = FALSE}
CopyS <-data.frame(aLD())
  tab3 <-table(CopyS$hh,CopyS$minute)
  tab3
  rowSums(tab3)
  chisq.test(tab3)
```

### nb duree

```{r nbDuree, echo = FALSE}
CopyS <-data.frame(aListes())
  plot(CopyS$nb.jour,main="nb d'ep par jour",type = "l",col="red",xlab = "date",ylab = "nb ep",xlim=c(0,36))
  
  plot(CopyS$nb.sem,main="nb d'ep par semaine",type = "l",col="red",xlab = "date",ylab = "nb ep",xlim=c(0,36))

  plot(CopyS$nb.mois,main="nb d'ep par mois",type = "l",col="red",xlab = "date",ylab = "nb ep",xlim=c(0,36))
```

### conclu

```{r concluG, echo = FALSE}
CopyS <-data.frame(copy.conclu())
#dataC <- data.frame(CopyS$nbCarConclu,CopyS$nbCarConcluBis,CopyS$jour_1,CopyS$date)
  
  plot(CopyS$nbCarConcluBis,main="nb de caracteres conclu",type = "l",col="red",xlab = "date",ylab = "nb car")
  lines(CopyS$nbCarConclu,type = "l",col="blue")
  
  plot(CopyS$ncb,main="nb de saisons conclu",type = "l",col="red",xlab = "date",ylab = "nb ds conclu")
  lines(CopyS$nc,type = "l",col="blue")
```

### max

```{r max2, echo = FALSE}
CopyS <- data.frame(copy.max())
main <- function(){
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  plot(CopyS$NBog,main="max",type = "l",col="red",xlab = "date",ylab = "nb")
  lines(CopyS$NBactuel,type = "l",col="blue")
}
suppressWarnings(main())
```

### nb tisaep duree

```{r pars, echo = FALSE}
CopyS <-data.frame(aPARS())
  
  plot(CopyS$j,main="nb de tisaep",type = "l",col="red",xlab = "date",ylab = "nb",ylim=c(0,30*1.1) )
  lines(CopyS$s,type = "l",col="blue")
  lines(CopyS$m,type = "l",col="violet")
  box()
  
```

### calendar

```{r cal2, echo=FALSE}

print("cal21")

df <- data.frame(aCal21())

barplot(table(df$sem1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem1))*1.1)
        )
box()

barplot(table(df$sem2),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week fin",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem2))*1.1)
        )
box()

barplot(table(df$sem3),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week debut",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem3))*1.1)
        )
box()

barplot(table(df$sem4),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week premder",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem4))*1.1)
        )
box()

print("calEc")

df2 <- data.frame(aCalEc())

barplot(table(df2$sem1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent)",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem1))*1.1)
        )
box()

barplot(table(df2$sem2),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) fin",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem2))*1.1)
        )
box()

barplot(table(df2$sem3),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) debut",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem3))*1.1)
        )
box()

barplot(table(df2$pays),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) pays",
        ylab = "nb pays",
        ylim=c(0,max(table(df2$pays))*1.1)
        )
box()

# max(table(df$sem1))*1.1
```

```{r cal, echo=FALSE}
df <- data.frame(aCal21())

layout(matrix(1:4,2,2))

barplot(table(df$sem1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem1))*1.1)
        )
box()

barplot(table(df$sem2),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week fin",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem2))*1.1)
        )
box()

barplot(table(df$sem3),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week debut",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem3))*1.1)
        )
box()

barplot(table(df$sem4),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week premder",
        ylab = "nb ep",
        ylim=c(0,max(table(df$sem4))*1.1)
        )
box()

df2 <- data.frame(aCalEc())

barplot(table(df2$sem1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent)",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem1))*1.1)
        )
box()

barplot(table(df2$sem2),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) fin",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem2))*1.1)
        )
box()

barplot(table(df2$sem3),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) debut",
        ylab = "nb ep",
        ylim=c(0,max(table(df2$sem3))*1.1)
        )
box()

barplot(table(df2$pays),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per week (recent) pays",
        ylab = "nb pays",
        ylim=c(0,max(table(df2$pays))*1.1)
        )
box()

# max(table(df$sem1))*1.1
```

### reste

```{r reste, echo=FALSE}
df <- data.frame(aReste())

barplot(table(df$pays),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="pays",
        ylab = "nb ep",
        ylim=c(0,max(table(df$pays))*1.1)
        )
box()

#barplot(table(df$rest),las = 2,col =brewer.pal(8, "Dark2"), main ="rest",ylab = "nb ep",ylim=c(0,max(table(df$rest))*1.1))
#box()


# max(table(df$sem1))*1.1
```

```{r regress0, eval=FALSE, include=FALSE}
### regression max
Prestige <- copy.max()
    Prestige <- as_tibble(Prestige)
     layout(matrix(1:4,2,2))
    # 1
scatterplot(NBog~NBactuel
, data=Prestige)

prest.lm1 <- lm(NBog~NBactuel, data=Prestige)
acf(residuals(prest.lm1), main="prest.lm1")
# durbinWatsonTest (prest.lm1)
plot(prest.lm1,2)
# shapiro.test(residuals(prest.lm1))
plot(prest.lm1, 3)
# ncvTest(prest.lm1)
plot(prest.lm1,1)
# influenceIndexPlot(prest.lm1)
```

```{r regress1, echo = FALSE, include=FALSE}
### regression1 nbCarConclu~nbCarConcluBis
# install.packages("car")
Prestige <- copy.conclu()
    Prestige <- as_tibble(Prestige)

    # as.tibble(Prestige)
     layout(matrix(1:4,2,2))
    # 1
scatterplot(nbCarConclu~nbCarConcluBis
, data=Prestige)
# 2
# scatterplot(nc~ncb, data=Prestige)
# 3
# scatterplot(nbCarConclu~nc, data=Prestige)
# 4
# scatterplot(nbCarConcluBis~ncb, data=Prestige)

prest.lm1 <- lm(nbCarConclu~nbCarConcluBis, data=Prestige)
acf(residuals(prest.lm1), main="prest.lm1")
# durbinWatsonTest (prest.lm1)
plot(prest.lm1,2)
# shapiro.test(residuals(prest.lm1))
plot(prest.lm1, 3)
# ncvTest(prest.lm1)
plot(prest.lm1,1)
# influenceIndexPlot(prest.lm1)
```

```{r regress2, echo = FALSE, include=FALSE}
### regression2 nc~ncb
# install.packages("car")
Prestige <- copy.conclu()
    Prestige <- as_tibble(Prestige)

    # as.tibble(Prestige)
    layout(matrix(1:4,2,2))
# 2
scatterplot(nc~ncb
, data=Prestige)

prest.lm1 <- lm(nc~ncb, data=Prestige)
acf(residuals(prest.lm1), main="prest.lm1")
# durbinWatsonTest (prest.lm1)
plot(prest.lm1,2)
# shapiro.test(residuals(prest.lm1))
plot(prest.lm1, 3)
# ncvTest(prest.lm1)
plot(prest.lm1,1)
```

```{r regress3, echo = FALSE, include=FALSE}
### regression3 nbCarConclu~nc
# install.packages("car")
Prestige <- copy.conclu()
    Prestige <- as_tibble(Prestige)

    # as.tibble(Prestige)
    layout(matrix(1:4,2,2))
# 3
scatterplot(nbCarConclu~nc
, data=Prestige)

prest.lm1 <- lm(nbCarConclu~nc, data=Prestige)
acf(residuals(prest.lm1), main="prest.lm1")
# durbinWatsonTest (prest.lm1)
plot(prest.lm1,2)
# shapiro.test(residuals(prest.lm1))
plot(prest.lm1, 3)
# ncvTest(prest.lm1)
plot(prest.lm1,1)
```

```{r regress4, echo = FALSE, include=FALSE}
### regression4 nbCarConcluBis~ncb
# install.packages("car")
Prestige <- copy.conclu()
    Prestige <- as_tibble(Prestige)

    # as.tibble(Prestige)
  layout(matrix(1:4,2,2))
# 4
scatterplot(nbCarConcluBis~ncb
, data=Prestige)

prest.lm1 <- lm(nbCarConcluBis~ncb, data=Prestige)
acf(residuals(prest.lm1), main="prest.lm1")
# durbinWatsonTest (prest.lm1)
plot(prest.lm1,2)
# shapiro.test(residuals(prest.lm1))
plot(prest.lm1, 3)
# ncvTest(prest.lm1)
plot(prest.lm1,1)
```

------------------------------------------------------------------------

::: {style="page-break-after: always; visibility: hidden"}
\pagebreak
:::

### en cours

```{r ecocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[1:6])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  sem <- CopyS %>% filter(occ.ECS >= 1)
  sem2 <- sem %>% arrange(desc(sem$occ.ECS))
  barplot(sem$occ.ECS, 
          las = 2, 
          names.arg = sem$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(sem$occ.ECS)*1.1))
  box()
  pie(sem2$occ.ECS,label=paste(sem2$en.cours,"",sem2$occ.ECS))
  print("mois")
  mois <- CopyS %>% filter(occ.ECM >= 1)
  mois2 <- mois %>% arrange(desc(mois$occ.ECM))
  barplot(mois$occ.ECM, 
          las = 2, 
          names.arg = mois$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(mois$occ.ECM)*1.1))
  box()
  pie(mois2$occ.ECM,label=paste(mois2$en.cours,"",mois2$occ.ECM))
  print("recent")
  rec <- CopyS %>% filter(occ.ECR >= 1)
  rec2 <- rec %>% arrange(desc(rec$occ.ECR))
  barplot(rec$occ.ECR, 
          las = 2, 
          names.arg = rec$en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(rec$occ.ECR)*1.1))
  box()
  pie(rec2$occ.ECR,label=paste(rec2$en.cours,"",rec2$occ.ECR))
  print("tout")
  barplot(CopyS$count, 
          las = 2, 
          names.arg = CopyS$tisa.en.cours,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$en.cours,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.ECR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

### termine

```{r terocc, echo=FALSE}
CopyS <- data.frame(aECocc())
CopyS <- data.frame(CopyS[7:12])
main <- function(){
  max <- 30
# CopyS <- data.frame()
  CopyS <- na.omit(CopyS)
  print("semaine")
  sem <- CopyS %>% filter(occ.FINIS >= 1)
  barplot(sem$occ.FINIS, 
          las = 2, 
          names.arg = sem$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top semaine",
          ylab = "Word frequencies",
          ylim=c(0,max(sem$occ.FINIS)*1.1))
  box()
  print("mois")
  mois <- CopyS %>% filter(occ.FINIM >= 1)
  barplot(mois$occ.FINIM, 
          las = 2, 
          names.arg = mois$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top mois",
          ylab = "Word frequencies",
          ylim=c(0,max(mois$occ.FINIM)*1.1))
  box()
  print("recent")
  barplot(CopyS$occ.FINIR, 
          las = 2, 
          names.arg = CopyS$fini,
          col =brewer.pal(8, "Dark2"), 
          main ="Top recent",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  print("tout")
  barplot(CopyS$count_1, 
          las = 2, 
          names.arg = CopyS$tisa.terminée,
          col =brewer.pal(8, "Dark2"), 
          main ="Top all",
          ylab = "Word frequencies",
          ylim=c(0,max(CopyS$count_1)*1.1))
  box()
  print("---")
  barplot(t(as.matrix(CopyS[2:4])), 
          las = 2, 
          names.arg = CopyS$fini,
          col =c("red","blue","green"), 
          main ="Top ---",
          ylab = "Word frequencies",
          beside = TRUE,
          ylim=c(0,max(CopyS$occ.FINIR)*1.1))
  box()
  legend('topright',fill=c("red","blue","green"),legend=c('recent','mois','sem'))
}
suppressWarnings(main())
```

### temps

```{r temps, echo=FALSE}

df <- data.frame(aLD())

# print("heures")
barplot(table(df$hh),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per hours",
        ylab = "nb ep",
        ylim=c(0,max(table(df$hh))*1.1)
        )
box()
# print("minutes")
barplot(table(df$minute),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="ep per minutes",
        ylab = "nb ep",
        ylim=c(0,max(table(df$minute))*1.1)
        )
box()

```

### accueil

```{r acc, echo=FALSE}

df <- data.frame(aLD())
layout(matrix(1:4,2,2))
# print("saison")
barplot(table(df$saison),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="saison",
        ylab = "nb ep",
        ylim=c(0,max(table(df$saison))*1.1)
        )
box()
# print("episode")
barplot(table(df$episode),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="episode",
        ylab = "nb ep",
        ylim=c(0,max(table(df$episode))*1.1)
        )
box()
# print("status")
barplot(table(df$status),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="status",
        ylab = "nb ep",
        ylim=c(0,max(table(df$status))*1.1)
        )
box()


```

### copy

```{r copy2, echo=FALSE}

df <- data.frame(aCopyScript())
layout(matrix(1:4,2,2))

# print("nb titre sem")
barplot(table(df$nrs),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre sem",
        ylab = "nb sem with x titles",
        ylim=c(0,max(table(df$nrs))*1.1)
        )
box()
# print("nb caractere sem")
barplot(table(df$nbCar),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb caractere sem",
        ylab = "nb sem with x car",
        ylim=c(0,max(table(df$nbCar))*1.1)
        )
box()
# print("nb titre mois")
barplot(table(df$nrm),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre mois",
        ylab = "nb mois with x titles",
        ylim=c(0,max(table(df$nrm))*1.1)
        )
box()

# print("nb caractere mois")
barplot(table(df$nbCar_1),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb caractere mois",
        ylab = "nb mois with x car",
        ylim=c(0,max(table(df$nbCar_1))*1.1)
        )
box()
layout(matrix(1:2,1,2))
# print("nb titre conclu")
barplot(table(df$nc),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre conclu",
        ylab = "nc",
        ylim=c(0,max(table(df$nc))*1.1)
        )
box()
# print("nb titre conclubis")
barplot(table(df$ncb),
        las = 2,
        col =brewer.pal(8, "Dark2"), 
        main ="nb titre conclubis",
        ylab = "ncb",
        ylim=c(0,max(table(df$ncb))*1.1)
        )
box()
```

------------------------------------------------------------------------

::: {style="page-break-after: always; visibility: hidden"}
\pagebreak
:::

## NETWORKS

```{r network1, echo=FALSE}

netw <- function(max=15){
  
df <- data.frame(listeCompl.ec())
df <- df[1:max,]

  ### CREATE NODES TABLE 
get_random_names <- function(n) { 
  unique_names <- distinct(df, en.cours, .keep_all = TRUE) 
  index <- sample(1:nrow(unique_names), n, replace = FALSE) 
  names <- unique_names[index, ] 
  names 
}

nodes <- get_random_names(max)


### CREATE LINKS TABLE 
# Create source and target vectors 
src <- sample(1:nrow(nodes), nrow(nodes)*2, replace = TRUE)  
target <- sample(1:nrow(nodes), nrow(nodes)*2, replace = TRUE)

# Merge vectors to form a single table 
links <- data.frame(src, target)

# Clean up 
links <- data.frame(src, target) %>%  
  filter(!(src == target)) 
links <- unique(links[c("src", "target")])


### PLOT NETWORK 
# Type cast to tbl_graph object
social_net_tbls <- tbl_graph(nodes = nodes, 
                             edges = links, 
                             directed = FALSE)

# Create the network 
social_net <- ggraph(social_net_tbls, layout = "stress") +
  geom_node_point(size = 2) +                                         
  geom_node_text(aes(label = en.cours), nudge_y = 0.05, nudge_x = 0.2)+ 
  geom_edge_link() +
  theme_void()

# Render the network 
  show(social_net)
  # 


}

netw(10) 
#dev.print(device = png, file = "network1_1.png", width = 600)
netw(10)
#dev.print(device = png, file = "network1_2.png", width = 600)
```

```{r corr , echo=FALSE}
### corr

```

### timing

```{r timing , echo=FALSE}
end_time<-Sys.time()
total_time <- end_time - begin_time
print(total_time)
begin_time2 <-Sys.time()
```
