---
title: "sumup"
output:
  html_document:
    df_print: paged
    toc: false
---

```{r setup, include = FALSE}
begin_time <-Sys.time()
suppressWarnings(source("./R/sources.R"))
library(vtable)
sumup <- function(i){
  print(i)
  print(z0n(i))
  # all data
  print(summary(z0u(i)))
  print("------------------------------------")
}
sumup2 <- function(i){
  print(i)
  print(z0n(i))
  # numeric data
  data_num <- select_if(z0u(i), is.numeric) 
  print(summary(data_num))
  print("------------------------------------")
}
```


[retour](./../index.html)  

<!-- -->
||||  
|---|---|---|  
|[allListe](./allListe.html)|[wordcloud](./wordcloud.html)|[graph](./mygraph.html)|  
|[sumup](./sumup.html)|[summary](./summary.html)|[sumUpAll](./sumUpAll.html)|


---


## SUMMARY

### 0
```{r stats0, echo=FALSE}
sumup2(1)
for (i in 3:9) {
  sumup2(i)
}
```

### 1
```{r stats1, echo=FALSE}
for (i in 10:19) {
  sumup2(i)
}
```

### 2
```{r stats2, echo=FALSE}
for (i in 20:26) {
  sumup2(i)
}
for (i in 28:29) {
  sumup2(i)
}
#sumup2(29)

```

### 3
```{r stats3, echo=FALSE}
sumup2(30)
for (i in 32:39) {
  sumup2(i)
}
```

### 4
```{r stats4, echo=FALSE}
for (i in 40:43) {
  sumup2(i)
}
for (i in 44:49) {
  sumup2(i)
}
```

### 5
```{r stats5, echo=FALSE}
for (i in 50:55) {
  sumup2(i)
}
#sumup2(59)
```


```{r stats6, echo=FALSE}
### 6
#sumup2(60)
```


## timing 
```{r timing , echo=FALSE}
end_time<-Sys.time()
total_time <- end_time - begin_time
print(total_time)
# begin_time <-Sys.time()
```
