---
title: "sumUpAll"
output:
  html_document:
    df_print: paged
    toc: false
---

```{r setup, include = FALSE}
begin_time <-Sys.time()
suppressWarnings(source("./R/sources.R"))
library(vtable)
sumup <- function(i){
  print(i)
  print(z13n(i))
  data_num <- select_if(z13u(i), is.numeric) 
  print(summary(data_num))
  print("------")
}
```


[retour](./../index.html)  

<!-- -->
||||  
|---|---|---|  
|[allListe](./allListe.html)|[wordcloud](./wordcloud.html)|[graph](./mygraph.html)|  
|[sumup](./sumup.html)|[summary](./summary.html)|[sumUpAll](./sumUpAll.html)|

---

## SUMMARY

### 0
```{r stats0, echo=FALSE}
for (i in 1:9) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 1
```{r stats1, echo=FALSE}
for (i in 10:14) {
  sumup(i)
}
for (i in 16:19) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 2
```{r stats2, echo=FALSE}
for (i in 20:29) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 3
```{r stats3, echo=FALSE}
for (i in 30:35) {
  sumup(i)
}
for (i in 37:39) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 4
```{r stats4, echo=FALSE}
for (i in 40:49) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 5
```{r stats5, echo=FALSE}
for (i in 50:59) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 6
```{r stats6, echo=FALSE}
for (i in 60:69) {
  sumup(i)
}
```

<div style="page-break-after: always; visibility: hidden"> 
\pagebreak 
</div>

### 7
```{r stats7, echo=FALSE}
for (i in 70:71) {
  sumup(i)
}
```

## timing 
```{r timing , echo=FALSE}
end_time<-Sys.time()
total_time <- end_time - begin_time
print(total_time)
# begin_time <-Sys.time()
```
